// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoALBMPG_7jlWhP06pfhjPAon0p5jCfA0',
    appId: '1:941560437199:web:5035b2ecb4a269f1001aba',
    messagingSenderId: '941560437199',
    projectId: 'chat-app-d2283',
    authDomain: 'chat-app-d2283.firebaseapp.com',
    storageBucket: 'chat-app-d2283.appspot.com',
    measurementId: 'G-XHZ3T4B9NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8JBSN9KpDgxc5BHRXRV_Zd6PpOZfdrg',
    appId: '1:941560437199:android:f8e05d00eb005e87001aba',
    messagingSenderId: '941560437199',
    projectId: 'chat-app-d2283',
    storageBucket: 'chat-app-d2283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5JFmOarJemkMtVbBBT4K1jaMuXu_iDZw',
    appId: '1:941560437199:ios:46b0ffbf6f343666001aba',
    messagingSenderId: '941560437199',
    projectId: 'chat-app-d2283',
    storageBucket: 'chat-app-d2283.appspot.com',
    iosClientId: '941560437199-euodri70b4ooknha2d5scb4hdcfe5ujh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5JFmOarJemkMtVbBBT4K1jaMuXu_iDZw',
    appId: '1:941560437199:ios:46b0ffbf6f343666001aba',
    messagingSenderId: '941560437199',
    projectId: 'chat-app-d2283',
    storageBucket: 'chat-app-d2283.appspot.com',
    iosClientId: '941560437199-euodri70b4ooknha2d5scb4hdcfe5ujh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
